main/base-kernel: fix run-kernel-d hook to work as intended

diff --git a/main/base-kernel/files/libexec/run-kernel-d b/main/base-kernel/files/libexec/run-kernel-d
--- a/main/base-kernel/files/libexec/run-kernel-d
+++ b/main/base-kernel/files/libexec/run-kernel-d
@@ -6,9 +6,6 @@ find -L /etc/kernel.d /usr/lib/kernel.d -maxdepth 1 -not -type d 2>/dev/null | \
   sed 's,.*/\(.*\),& \1,' | sort -k2 -s | uniq -f1 | cut -d' ' -f1 | \
   while read hook; do
     if [ -x "$hook" ]; then
-        /bin/sh "$hook"
-    else
-        "$hook"
+        "$hook" || echo "FAILED: $hook"
     fi
-    [ $? -eq 0 ] || echo "FAILED: $hook"
 done
