main/base-kernel: fix hook error reporting

diff --git a/main/base-kernel/files/libexec/run-kernel-d b/main/base-kernel/files/libexec/run-kernel-d
--- a/main/base-kernel/files/libexec/run-kernel-d
+++ b/main/base-kernel/files/libexec/run-kernel-d
@@ -10,5 +10,5 @@ find -L /etc/kernel.d /usr/lib/kernel.d -maxdepth 1 -not -type d 2>/dev/null | \
     else
         "$hook"
     fi
-    [ $? -eq 0 ] || echo "FAILED: $line"
+    [ $? -eq 0 ] || echo "FAILED: $hook"
 done
