main/initramfs-tools: update to 0.145

diff --git a/main/initramfs-tools/patches/0005-general-portability-fixes-for-bsdutils-and-musl.patch b/main/initramfs-tools/patches/0005-general-portability-fixes-for-bsdutils-and-musl.patch
--- a/main/initramfs-tools/patches/0005-general-portability-fixes-for-bsdutils-and-musl.patch
+++ b/main/initramfs-tools/patches/0005-general-portability-fixes-for-bsdutils-and-musl.patch
@@ -1,19 +1,19 @@
-From c94327f8c4420e244b3e5a22170b971ad53dc7e3 Mon Sep 17 00:00:00 2001
+From b433d207df2f1633b30be7f0f6ad79c0bacb3f42 Mon Sep 17 00:00:00 2001
 From: q66 <q66@chimera-linux.org>
 Date: Mon, 3 Jun 2024 16:45:18 +0200
-Subject: [PATCH 5/8] general portability fixes for bsdutils and musl
+Subject: [PATCH 5/9] general portability fixes for bsdutils and musl
 
 ---
- hook-functions | 53 +++++++++++++++++++++++---------------------------
- mkinitramfs    | 21 ++++----------------
- unmkinitramfs  | 12 ++++++------
- 3 files changed, 34 insertions(+), 52 deletions(-)
+ hook-functions | 56 +++++++++++++++++++++++---------------------------
+ mkinitramfs    | 24 ++++++----------------
+ unmkinitramfs  | 12 +++++------
+ 3 files changed, 38 insertions(+), 54 deletions(-)
 
 diff --git a/hook-functions b/hook-functions
-index d30ff25..e221f95 100644
+index ca5e1e2..55ad3c8 100644
 --- a/hook-functions
 +++ b/hook-functions
-@@ -166,6 +166,19 @@ _sanitize_target() {
+@@ -167,6 +167,19 @@ _sanitize_target() {
  	printf "%s" "${target}"
  }
  
@@ -33,16 +33,26 @@ index d30ff25..e221f95 100644
  # $1 = file type (for logging)
  # $2 = file to copy to initramfs
  # $3 (optional) Name for the file on the initramfs
-@@ -173,7 +186,7 @@ _sanitize_target() {
+@@ -174,7 +187,7 @@ _sanitize_target() {
  # If the target exists, we leave it and return 1.
  # On any other error, we return >1.
  copy_file() {
 -	local type src target link_target
-+	local type src target link_target relp
++	local type src target link_target link_path relp
  
  	type="${1}"
  	src="${2}"
-@@ -209,7 +222,8 @@ copy_file() {
+@@ -205,7 +218,8 @@ copy_file() {
+ 	# too.  We don't need to replicate a chain of links completely;
+ 	# just link directly to the ultimate target.
+ 	link_target="$(readlink -f "${src}")" || return $(($? + 1))
+-	if [ "${link_target}" != "$(realpath -s "$src")" ]; then
++	link_path=$(sh -c 'pv=$(dirname "$1"); pb=$(basename "$1"); cd "$pv"; echo "$(pwd)/$pb"' sh "$src")
++	if [ "${link_target}" != "${link_path}" ]; then
+ 		# Update source for the copy
+ 		src="${link_target}"
+ 
+@@ -217,7 +231,8 @@ copy_file() {
  
  			# Create a relative link so it always points
  			# to the right place
@@ -52,7 +62,7 @@ index d30ff25..e221f95 100644
  		fi
  
  		# Copy the link target if it doesn't already exist
-@@ -236,30 +250,10 @@ copy_exec() {
+@@ -244,30 +259,10 @@ copy_exec() {
  	copy_file binary "${src}" "${target}" || return $(($? - 1))
  
  	# Copy the dependant libraries
@@ -87,7 +97,7 @@ index d30ff25..e221f95 100644
  		copy_file binary "${x}" || {
  			ret=$?
  			[ ${ret} = 1 ] || return $((ret - 1))
-@@ -307,7 +301,8 @@ copy_modules_dir()
+@@ -315,7 +310,8 @@ copy_modules_dir()
  	done
  
  	# shellcheck disable=SC2044
@@ -97,7 +107,7 @@ index d30ff25..e221f95 100644
  		modules="$modules ${kmod%%.*}"
  	done
  	# shellcheck disable=SC2086
-@@ -403,8 +398,8 @@ block_dev_mod_add()
+@@ -411,8 +407,8 @@ block_dev_mod_add()
  	dev_node="$1"
  
  	# Look up device number and convert to decimal as it appears in sysfs
@@ -109,10 +119,10 @@ index d30ff25..e221f95 100644
  	# Look up device in sysfs
  	dev_sys_path="/sys/dev/block/$dev_num"
 diff --git a/mkinitramfs b/mkinitramfs
-index 2c60ee0..459b421 100755
+index efb3f78..c15833c 100755
 --- a/mkinitramfs
 +++ b/mkinitramfs
-@@ -380,16 +380,16 @@ add_builtin_firmware
+@@ -386,16 +386,16 @@ add_builtin_firmware
  cp -p /usr/share/initramfs-tools/init "${DESTDIR}/init"
  
  # add existant boot scripts
@@ -133,7 +143,7 @@ index 2c60ee0..459b421 100755
  	[ -d "${DESTDIR}/scripts/$(dirname "${b}")" ] \
  		|| mkdir -p "${DESTDIR}/scripts/$(dirname "${b}")"
  	cp -p "${CONFDIR}/scripts/${b}" "${DESTDIR}/scripts/$(dirname "${b}")/"
-@@ -461,19 +461,6 @@ done
+@@ -467,19 +467,6 @@ done
  depmod -a -b "${DESTDIR}" "${version}"
  rm -f "${DESTDIR}/lib/modules/${version}"/modules.*map
  
@@ -153,6 +163,17 @@ index 2c60ee0..459b421 100755
  # Apply DSDT to initramfs
  if [ -e "${CONFDIR}/DSDT.aml" ]; then
  	copy_file DSDT "${CONFDIR}/DSDT.aml"
+@@ -518,8 +505,9 @@ fi
+ 		fi
+ 
+ 		{
++			cd "$DESTDIR"
+ 			# shellcheck disable=SC2086
+-			cpio --quiet $cpio_owner_root $cpio_reproducible -o -H newc -D "${DESTDIR}" <"${__TMPMAINFILES}" ||
++			cpio --quiet $cpio_owner_root $cpio_reproducible -o -H newc <"${__TMPMAINFILES}" ||
+ 				{ echo "E: mkinitramfs failure cpio $?" >&2; echo 1 >&3; exit; }
+ 		} | $compress -c ||
+ 			{ echo "E: mkinitramfs failure $compress $?" >&2; echo 1 >&3; exit; }
 diff --git a/unmkinitramfs b/unmkinitramfs
 index a296029..b3b101d 100755
 --- a/unmkinitramfs
@@ -197,5 +218,5 @@ index a296029..b3b101d 100755
  eval set -- "$OPTIONS"
  
 -- 
-2.45.2
+2.46.0
 
diff --git a/main/initramfs-tools/patches/0007-use-fstype-from-klibc-kinit-standalone.patch b/main/initramfs-tools/patches/0007-use-fstype-from-klibc-kinit-standalone.patch
--- a/main/initramfs-tools/patches/0007-use-fstype-from-klibc-kinit-standalone.patch
+++ b/main/initramfs-tools/patches/0007-use-fstype-from-klibc-kinit-standalone.patch
@@ -1,7 +1,7 @@
-From dc2fe64a86ce0ab3f793034858eb6b90e9010d01 Mon Sep 17 00:00:00 2001
+From b57e0e94d24835920a777ce605d4cb9629fb5210 Mon Sep 17 00:00:00 2001
 From: q66 <q66@chimera-linux.org>
-Date: Wed, 20 Jul 2022 04:06:22 +0200
-Subject: [PATCH 7/8] use fstype from klibc-kinit-standalone
+Date: Wed, 28 Aug 2024 14:01:17 +0200
+Subject: [PATCH 7/9] use fstype from klibc-kinit-standalone
 
 ---
  hook-functions | 2 +-
@@ -9,10 +9,10 @@ Subject: [PATCH 7/8] use fstype from klibc-kinit-standalone
  2 files changed, 2 insertions(+), 2 deletions(-)
 
 diff --git a/hook-functions b/hook-functions
-index e221f95..1cf0e41 100644
+index 55ad3c8..f6a49ca 100644
 --- a/hook-functions
 +++ b/hook-functions
-@@ -520,7 +520,7 @@ dep_add_modules_mount()
+@@ -535,7 +535,7 @@ dep_add_modules_mount()
  	fi
  
  	# do not trust mount, check superblock
@@ -22,18 +22,18 @@ index e221f95..1cf0e41 100644
  	# check that fstype fs recognition
  	if [ "${FSTYPE}" = "unknown" ]; then
 diff --git a/hooks/fsck b/hooks/fsck
-index 012c97e..26a50d5 100755
+index 3479dfc..2f219d2 100755
 --- a/hooks/fsck
 +++ b/hooks/fsck
-@@ -53,7 +53,7 @@ get_fsck_type_fstab () {
+@@ -54,7 +54,7 @@ get_fsck_type_fstab () {
  		if [ "${MNT_DIR}" = "/" ] || [ "${MNT_TYPE}" = "auto" ]; then
- 			MNT_FSNAME="$(resolve_device "${MNT_FSNAME}")"
+ 			device="$(resolve_device "${MNT_FSNAME}")"
  			# shellcheck disable=SC2317
 -			fstype() { "/usr/lib/klibc/bin/fstype" "$@"; }
 +			fstype() { "/usr/libexec/kinit-standalone/fstype" "$@"; }
- 			if ! get_fstype "${MNT_FSNAME}"; then
- 				echo "W: Couldn't identify type of $2 file system for fsck hook" >&2
+ 			if ! get_fstype "${device}"; then
+ 				echo "W: Couldn't identify type of $2 file system '$MNT_FSNAME' for fsck hook" >&2
  			fi
 -- 
-2.45.2
+2.46.0
 
