main/cryptsetup-scripts: update to 2.7.2.2

diff --git a/main/cryptsetup-scripts/patches/0004-remove-lsb-script-dependency-from-cryptdisks.patch b/main/cryptsetup-scripts/patches/0004-remove-lsb-script-dependency-from-cryptdisks.patch
--- a/main/cryptsetup-scripts/patches/0004-remove-lsb-script-dependency-from-cryptdisks.patch
+++ b/main/cryptsetup-scripts/patches/0004-remove-lsb-script-dependency-from-cryptdisks.patch
@@ -1,14 +1,15 @@
-From 20f096dcf93c65b105b71e364a108c56cab30baf Mon Sep 17 00:00:00 2001
+From a78d7f37c738ef1e9e0194d330fc4bf15b4ea41b Mon Sep 17 00:00:00 2001
 From: q66 <q66@chimera-linux.org>
 Date: Fri, 17 Mar 2023 19:55:50 +0100
 Subject: [PATCH 4/4] remove lsb script dependency from cryptdisks
 
 ---
- debian/cryptdisks-functions     | 49 ++++-----------------------------
- debian/functions                |  3 +-
- debian/scripts/cryptdisks_start |  4 +--
- debian/scripts/cryptdisks_stop  |  5 +---
- 4 files changed, 9 insertions(+), 52 deletions(-)
+ debian/cryptdisks-functions                   | 49 +++----------------
+ debian/functions                              |  3 +-
+ .../scripts/local-bottom/cryptopensc          |  3 +-
+ debian/scripts/cryptdisks_start               |  6 +--
+ debian/scripts/cryptdisks_stop                |  5 +-
+ 5 files changed, 11 insertions(+), 55 deletions(-)
 
 diff --git a/debian/cryptdisks-functions b/debian/cryptdisks-functions
 index c35b284..bd535be 100644
@@ -195,7 +196,7 @@ index c35b284..bd535be 100644
      fi
  }
 diff --git a/debian/functions b/debian/functions
-index 45e6f41..d6039a6 100644
+index f6fa2aa..c7860e8 100644
 --- a/debian/functions
 +++ b/debian/functions
 @@ -452,8 +452,7 @@ crypttab_key_check() {
@@ -208,11 +209,24 @@ index 45e6f41..d6039a6 100644
      fi
  }
  
+diff --git a/debian/initramfs/scripts/local-bottom/cryptopensc b/debian/initramfs/scripts/local-bottom/cryptopensc
+index 22406bc..9a0daf9 100644
+--- a/debian/initramfs/scripts/local-bottom/cryptopensc
++++ b/debian/initramfs/scripts/local-bottom/cryptopensc
+@@ -26,7 +26,6 @@ fi
+ 
+ if PID="$(cat /run/pcscd.pid)" 2>/dev/null &&
+         [ "$(readlink -f "/proc/$PID/exe")" = "/usr/bin/pcscd" ]; then
+-    log_begin_msg "Stopping pcscd"
++    echo "Stopping pcscd"
+     kill -TERM "$PID"
+-    log_end_msg
+ fi
 diff --git a/debian/scripts/cryptdisks_start b/debian/scripts/cryptdisks_start
-index d857fd9..8e3f852 100644
+index d857fd9..03dad01 100644
 --- a/debian/scripts/cryptdisks_start
 +++ b/debian/scripts/cryptdisks_start
-@@ -37,11 +37,10 @@ done
+@@ -37,17 +37,16 @@ done
  [ $# -gt 0 ] || usage 1
  
  if [ $(id -u) -ne 0 ]; then
@@ -225,6 +239,13 @@ index d857fd9..8e3f852 100644
  mount_fs
  
  rv=0
+ for name in "$@"; do
+     if ! crypttab_find_entry --quiet "$name"; then
+-        device_msg "$name" "failed, not found in crypttab"
++        printf "%s %s\n" "$name" "failed, not found in crypttab"
+         rv=1
+     else
+         if [ -n "$CRYPTTAB_EXTRA_OPTIONS" ]; then
 @@ -59,5 +58,4 @@ for name in "$@"; do
  done
  umount_fs
@@ -254,5 +275,5 @@ index 8fb7d68..48c7c32 100644
 -log_action_end_msg $rv
  exit $rv
 -- 
-2.43.0
+2.45.2
 
